// Generated by capnpc-zig
// Source: proof.capnp

const std = @import("std");
const capnpc = @import("capnpc-zig");
const message = capnpc.message;
const schema = capnpc.schema;

pub const CAPNP_SCHEMA_MANIFEST_JSON: []const u8 = "{\"schema\":\"proof.capnp\",\"module\":\"proof\",\"serde\":[{\"id\":14694040388961476695,\"type_name\":\"BucketProof\",\"to_json_export\":\"capnp_proof_bucket_proof_to_json\",\"from_json_export\":\"capnp_proof_bucket_proof_from_json\"},{\"id\":16183530348409898003,\"type_name\":\"ChainLevel\",\"to_json_export\":\"capnp_proof_chain_level_to_json\",\"from_json_export\":\"capnp_proof_chain_level_from_json\"},{\"id\":18350906904536974067,\"type_name\":\"Hash\",\"to_json_export\":\"capnp_proof_hash_to_json\",\"from_json_export\":\"capnp_proof_hash_from_json\"},{\"id\":11040269344464418071,\"type_name\":\"SlotPlacement\",\"to_json_export\":\"capnp_proof_slot_placement_to_json\",\"from_json_export\":\"capnp_proof_slot_placement_from_json\"},{\"id\":9360191887109431276,\"type_name\":\"Step\",\"to_json_export\":\"capnp_proof_step_to_json\",\"from_json_export\":\"capnp_proof_step_from_json\"},{\"id\":9877308517675603538,\"type_name\":\"VisibleProof\",\"to_json_export\":\"capnp_proof_visible_proof_to_json\",\"from_json_export\":\"capnp_proof_visible_proof_from_json\"}]}";
pub fn capnpSchemaManifestJson() []const u8 {
    return CAPNP_SCHEMA_MANIFEST_JSON;
}

pub const Hash = struct {
    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn hasBytes(self: Reader) bool {
            return !self._reader.isPointerNull(0);
        }

        pub fn getBytes(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return &[_]u8{};
            return try self._reader.readData(0);
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(0, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn hasBytes(self: Builder) bool {
            return !self._builder.isPointerNull(0);
        }

        pub fn setBytes(self: *Builder, value: []const u8) !void {
            try self._builder.writeData(0, value);
        }

    };
};

pub const Step = struct {
    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn hasHash(self: Reader) bool {
            return !self._reader.isPointerNull(0);
        }

        pub fn getHash(self: Reader) !Hash.Reader {
            if (self._reader.isPointerNull(0)) return Hash.Reader{ ._reader = self._reader.emptyStruct() };
            const value = try self._reader.readStruct(0);
            return Hash.Reader{ ._reader = value };
        }

        pub fn getRight(self: Reader) !bool {
            return self._reader.readBool(0, 0) != false;
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn hasHash(self: Builder) bool {
            return !self._builder.isPointerNull(0);
        }

        pub fn initHash(self: *Builder) !Hash.Builder {
            const builder = try self._builder.initStruct(0, 0, 1);
            return Hash.Builder{ ._builder = builder };
        }

        pub fn setRight(self: *Builder, value: bool) !void {
            self._builder.writeBool(0, 0, value != false);
        }

    };
};

pub const BucketProof = struct {
    const StructListReader = message.typed_list_helpers.StructListReader;
    const StructListBuilder = message.typed_list_helpers.StructListBuilder;

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn hasBlock(self: Reader) bool {
            return !self._reader.isPointerNull(0);
        }

        pub fn getBlock(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return &[_]u8{};
            return try self._reader.readData(0);
        }

        pub fn getBlockIndex(self: Reader) !u64 {
            return self._reader.readU64(0);
        }

        pub fn getBlockCount(self: Reader) !u64 {
            return self._reader.readU64(8);
        }

        pub fn getRecordCount(self: Reader) !u64 {
            return self._reader.readU64(16);
        }

        pub fn hasPath(self: Reader) bool {
            return !self._reader.isPointerNull(1);
        }

        pub fn getPath(self: Reader) !StructListReader(Step) {
            if (self._reader.isPointerNull(1)) return StructListReader(Step){ ._list = self._reader.emptyStructList() };
            const raw = try self._reader.readStructList(1);
            return StructListReader(Step){ ._list = raw };
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(3, 2);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn hasBlock(self: Builder) bool {
            return !self._builder.isPointerNull(0);
        }

        pub fn setBlock(self: *Builder, value: []const u8) !void {
            try self._builder.writeData(0, value);
        }

        pub fn setBlockIndex(self: *Builder, value: u64) !void {
            self._builder.writeU64(0, @bitCast(value));
        }

        pub fn setBlockCount(self: *Builder, value: u64) !void {
            self._builder.writeU64(8, @bitCast(value));
        }

        pub fn setRecordCount(self: *Builder, value: u64) !void {
            self._builder.writeU64(16, @bitCast(value));
        }

        pub fn hasPath(self: Builder) bool {
            return !self._builder.isPointerNull(1);
        }

        pub fn initPath(self: *Builder, element_count: u32) !StructListBuilder(Step) {
            const raw = try self._builder.writeStructList(1, element_count, 1, 1);
            return StructListBuilder(Step){ ._list = raw };
        }

    };
};

pub const ChainLevel = struct {
    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn hasCurr(self: Reader) bool {
            return !self._reader.isPointerNull(0);
        }

        pub fn getCurr(self: Reader) !Hash.Reader {
            if (self._reader.isPointerNull(0)) return Hash.Reader{ ._reader = self._reader.emptyStruct() };
            const value = try self._reader.readStruct(0);
            return Hash.Reader{ ._reader = value };
        }

        pub fn hasSnap(self: Reader) bool {
            return !self._reader.isPointerNull(1);
        }

        pub fn getSnap(self: Reader) !Hash.Reader {
            if (self._reader.isPointerNull(1)) return Hash.Reader{ ._reader = self._reader.emptyStruct() };
            const value = try self._reader.readStruct(1);
            return Hash.Reader{ ._reader = value };
        }

        pub fn hasNext(self: Reader) bool {
            return !self._reader.isPointerNull(2);
        }

        pub fn getNext(self: Reader) !Hash.Reader {
            if (self._reader.isPointerNull(2)) return Hash.Reader{ ._reader = self._reader.emptyStruct() };
            const value = try self._reader.readStruct(2);
            return Hash.Reader{ ._reader = value };
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(0, 3);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn hasCurr(self: Builder) bool {
            return !self._builder.isPointerNull(0);
        }

        pub fn initCurr(self: *Builder) !Hash.Builder {
            const builder = try self._builder.initStruct(0, 0, 1);
            return Hash.Builder{ ._builder = builder };
        }

        pub fn hasSnap(self: Builder) bool {
            return !self._builder.isPointerNull(1);
        }

        pub fn initSnap(self: *Builder) !Hash.Builder {
            const builder = try self._builder.initStruct(1, 0, 1);
            return Hash.Builder{ ._builder = builder };
        }

        pub fn hasNext(self: Builder) bool {
            return !self._builder.isPointerNull(2);
        }

        pub fn initNext(self: *Builder) !Hash.Builder {
            const builder = try self._builder.initStruct(2, 0, 1);
            return Hash.Builder{ ._builder = builder };
        }

    };
};

pub const SlotPlacement = struct {
    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getSlotLevel(self: Reader) !u32 {
            return self._reader.readU32(0);
        }

        pub fn getSlotSnapshot(self: Reader) !bool {
            return self._reader.readBool(4, 0) != false;
        }

        pub fn hasBucket(self: Reader) bool {
            return !self._reader.isPointerNull(0);
        }

        pub fn getBucket(self: Reader) !BucketProof.Reader {
            if (self._reader.isPointerNull(0)) return BucketProof.Reader{ ._reader = self._reader.emptyStruct() };
            const value = try self._reader.readStruct(0);
            return BucketProof.Reader{ ._reader = value };
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(1, 1);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setSlotLevel(self: *Builder, value: u32) !void {
            self._builder.writeU32(0, @bitCast(value));
        }

        pub fn setSlotSnapshot(self: *Builder, value: bool) !void {
            self._builder.writeBool(4, 0, value != false);
        }

        pub fn hasBucket(self: Builder) bool {
            return !self._builder.isPointerNull(0);
        }

        pub fn initBucket(self: *Builder) !BucketProof.Builder {
            const builder = try self._builder.initStruct(0, 3, 2);
            return BucketProof.Builder{ ._builder = builder };
        }

    };
};

pub const VisibleProof = struct {
    const StructListReader = message.typed_list_helpers.StructListReader;
    const StructListBuilder = message.typed_list_helpers.StructListBuilder;

    pub const Reader = struct {
        _reader: message.StructReader,

        pub fn init(msg: *const message.Message) !Reader {
            const root = try msg.getRootStruct();
            return .{ ._reader = root };
        }

        pub fn wrap(reader: message.StructReader) Reader {
            return .{ ._reader = reader };
        }

        pub fn getTable(self: Reader) !u32 {
            return self._reader.readU32(0);
        }

        pub fn hasKey(self: Reader) bool {
            return !self._reader.isPointerNull(0);
        }

        pub fn getKey(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(0)) return &[_]u8{};
            return try self._reader.readData(0);
        }

        pub fn hasValue(self: Reader) bool {
            return !self._reader.isPointerNull(1);
        }

        pub fn getValue(self: Reader) ![]const u8 {
            if (self._reader.isPointerNull(1)) return &[_]u8{};
            return try self._reader.readData(1);
        }

        pub fn getAbsent(self: Reader) !bool {
            return self._reader.readBool(4, 0) != false;
        }

        pub fn hasYounger(self: Reader) bool {
            return !self._reader.isPointerNull(2);
        }

        pub fn getYounger(self: Reader) !StructListReader(SlotPlacement) {
            if (self._reader.isPointerNull(2)) return StructListReader(SlotPlacement){ ._list = self._reader.emptyStructList() };
            const raw = try self._reader.readStructList(2);
            return StructListReader(SlotPlacement){ ._list = raw };
        }

        pub fn hasDeciding(self: Reader) bool {
            return !self._reader.isPointerNull(3);
        }

        pub fn getDeciding(self: Reader) !SlotPlacement.Reader {
            if (self._reader.isPointerNull(3)) return SlotPlacement.Reader{ ._reader = self._reader.emptyStruct() };
            const value = try self._reader.readStruct(3);
            return SlotPlacement.Reader{ ._reader = value };
        }

        pub fn hasSchemaHash(self: Reader) bool {
            return !self._reader.isPointerNull(4);
        }

        pub fn getSchemaHash(self: Reader) !Hash.Reader {
            if (self._reader.isPointerNull(4)) return Hash.Reader{ ._reader = self._reader.emptyStruct() };
            const value = try self._reader.readStruct(4);
            return Hash.Reader{ ._reader = value };
        }

        pub fn hasProfileHash(self: Reader) bool {
            return !self._reader.isPointerNull(5);
        }

        pub fn getProfileHash(self: Reader) !Hash.Reader {
            if (self._reader.isPointerNull(5)) return Hash.Reader{ ._reader = self._reader.emptyStruct() };
            const value = try self._reader.readStruct(5);
            return Hash.Reader{ ._reader = value };
        }

        pub fn getAdvance(self: Reader) !u64 {
            return self._reader.readU64(8);
        }

        pub fn hasLevels(self: Reader) bool {
            return !self._reader.isPointerNull(6);
        }

        pub fn getLevels(self: Reader) !StructListReader(ChainLevel) {
            if (self._reader.isPointerNull(6)) return StructListReader(ChainLevel){ ._list = self._reader.emptyStructList() };
            const raw = try self._reader.readStructList(6);
            return StructListReader(ChainLevel){ ._list = raw };
        }

    };

    pub const Builder = struct {
        _builder: message.StructBuilder,

        pub fn init(msg: *message.MessageBuilder) !Builder {
            const builder = try msg.allocateStruct(2, 7);
            return .{ ._builder = builder };
        }

        pub fn wrap(builder: message.StructBuilder) Builder {
            return .{ ._builder = builder };
        }

        pub fn setTable(self: *Builder, value: u32) !void {
            self._builder.writeU32(0, @bitCast(value));
        }

        pub fn hasKey(self: Builder) bool {
            return !self._builder.isPointerNull(0);
        }

        pub fn setKey(self: *Builder, value: []const u8) !void {
            try self._builder.writeData(0, value);
        }

        pub fn hasValue(self: Builder) bool {
            return !self._builder.isPointerNull(1);
        }

        pub fn setValue(self: *Builder, value: []const u8) !void {
            try self._builder.writeData(1, value);
        }

        pub fn setAbsent(self: *Builder, value: bool) !void {
            self._builder.writeBool(4, 0, value != false);
        }

        pub fn hasYounger(self: Builder) bool {
            return !self._builder.isPointerNull(2);
        }

        pub fn initYounger(self: *Builder, element_count: u32) !StructListBuilder(SlotPlacement) {
            const raw = try self._builder.writeStructList(2, element_count, 1, 1);
            return StructListBuilder(SlotPlacement){ ._list = raw };
        }

        pub fn hasDeciding(self: Builder) bool {
            return !self._builder.isPointerNull(3);
        }

        pub fn initDeciding(self: *Builder) !SlotPlacement.Builder {
            const builder = try self._builder.initStruct(3, 1, 1);
            return SlotPlacement.Builder{ ._builder = builder };
        }

        pub fn hasSchemaHash(self: Builder) bool {
            return !self._builder.isPointerNull(4);
        }

        pub fn initSchemaHash(self: *Builder) !Hash.Builder {
            const builder = try self._builder.initStruct(4, 0, 1);
            return Hash.Builder{ ._builder = builder };
        }

        pub fn hasProfileHash(self: Builder) bool {
            return !self._builder.isPointerNull(5);
        }

        pub fn initProfileHash(self: *Builder) !Hash.Builder {
            const builder = try self._builder.initStruct(5, 0, 1);
            return Hash.Builder{ ._builder = builder };
        }

        pub fn setAdvance(self: *Builder, value: u64) !void {
            self._builder.writeU64(8, @bitCast(value));
        }

        pub fn hasLevels(self: Builder) bool {
            return !self._builder.isPointerNull(6);
        }

        pub fn initLevels(self: *Builder, element_count: u32) !StructListBuilder(ChainLevel) {
            const raw = try self._builder.writeStructList(6, element_count, 0, 3);
            return StructListBuilder(ChainLevel){ ._list = raw };
        }

    };
};

